name: flutter_application_2
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  go_router: ^7.0.0
  provider: ^6.0.4
  window_manager:
  logging: ^1.0.0
  games_services: ^4.0.1
  in_app_purchase: ^3.0.0
  shared_preferences: ^2.0.0
  google_mobile_ads: ^1.2.0
  audioplayers: ^3.0.0
  firebase_core: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
